# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 850a9dafb50bf0271c11d5a0425c626a00f7066c8d7e0e8fe2f31aec63937e6b646179eb18a1f2764e1ebc2d488036aaada0eeb87762757664d6f955c92541d0

test:
  secret_key_base: 8c7c40f2be78dc2d39b3c4b01b89dac9bd6823a889e291ddc63147c1e041dca8faf143ac33519cbddd13f93a1d72aa02e508922813db7f2b2250f95c25764c6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
